language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t tyrelof/docker-react -f Dockerfile.dev .

script:
    - docker run -it -t tyrelof/docker-react npm run test -- --coverage