language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t tyrelof/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true tyrelof/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-1-567540846696"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $aws_access_key
    secret_access_key:
        secure: "$aws_secret_key"